### ISSUE TITLE
Got `Stack smashing protect failure`

### ISSUE THREAD

**Issue by t0ny-peng** [timmo001/ESP8266-MQTT-JSON-Lights#12]
# Description
I only have a lolin32 board so I have to modify the `platformio.ini`. Here's what I changed to:
```ini
[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino
lib_deps = ArduinoJson, PubSubClient, WS2812FX

upload_port = /dev/tty.SLAB_USBtoUART
monitor_port = /dev/tty.SLAB_USBtoUART
monitor_speed = 115200
```
... and also the header files in `main.cpp`,
```cpp
#include "setup.h"
#include <ArduinoJson.h>
#include <ArduinoOTA.h>
#include <ESPmDNS.h>
#include <PubSubClient.h>
#include <WS2812FX.h>
#include <WiFi.h>
#include <WiFiUdp.h>
```
The build process is ok. But after I flashed the firmware into lolin32 and started the serial monitor, here's what I get. 
```log
WiFi connected
IP address: 192.168.0.51
Ready
Attempting MQTT connection...connected

Stack smashing protect failure!

abort() was called at PC 0x400e2020 on core 1

Backtrace: 0x4008c794:0x3ffb1ef0 0x4008c9c5:0x3ffb1f10 0x400e2020:0x3ffb1f30 0x400d388e:0x3ffb1f50 0x400d38a4:0x3ffb1f90 0x400d9fa9:0x3ffb1fb0 0x4008ea15:0x3ffb1fd0

Rebooting...
ets Jun  8 2016 00:22:57
```

Do you have any idea where to look into? Thanks.

**Comment by timmo001** [comment]
Yes, I've had this before with an esp32 board. They have some kind of build in protection called 'stack smashing protection mode' which crashes the board. Others would probably have a better understanding of it than me.
