### ISSUE TITLE
Unanble to complie or open file in Ardunio IDE

### ISSUE THREAD

**Issue by Ameengray** [timmo001/ESP8266-MQTT-JSON-Lights#14]
# Description
Unable to open file in ardunio ide. Considering you are using node MCU or esp, it would be great if you could have the ino files in the directory as well. How can i compile this in Ardunio IDE ?

**Comment by timmo001** [comment]
This project is made for PlatformIO, not the Arduino IDE. Please use that instead:

https://github.com/timmo001/ESP8266-MQTT-JSON-Lights#software-setup


<blockquote><img src="https://avatars0.githubusercontent.com/u/28114703?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/timmo001/ESP8266-MQTT-JSON-Lights">timmo001/ESP8266-MQTT-JSON-Lights</a></strong></div><div>ESP8266 MQTT JSON Lights. Supports brightness, effects, speed and OTA uploads. Works with MQTT JSON and Home Assistant - timmo001/ESP8266-MQTT-JSON-Lights</div></blockquote>
